import {env,optionalEnv} from "./env";
let cachedToken:{token:string;expiresAt:number}|null=null;
export async function getBlizzardToken(){if(cachedToken&&cachedToken.expiresAt>Date.now()+60000)return cachedToken.token;const region=optionalEnv("BLIZZARD_REGION","us");const id=env("BLIZZARD_CLIENT_ID");const secret=env("BLIZZARD_CLIENT_SECRET");const res=await fetch(`https://${region}.battle.net/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials",cache:"no-store"});if(!res.ok)throw new Error(`Blizzard OAuth failed ${res.status}: ${await res.text()}`);const data=await res.json();cachedToken={token:data.access_token,expiresAt:Date.now()+(data.expires_in||3600)*1000};return cachedToken.token;}
export async function blizzardGet(path:string){const region=optionalEnv("BLIZZARD_REGION","us");const ns=optionalEnv("BLIZZARD_NAMESPACE","dynamic-classicann-us");const locale=optionalEnv("BLIZZARD_LOCALE","en_US");const token=await getBlizzardToken();const url=new URL(`https://${region}.api.blizzard.com${path}`);if(!url.searchParams.has("namespace"))url.searchParams.set("namespace",ns);if(!url.searchParams.has("locale"))url.searchParams.set("locale",locale);const res=await fetch(url.toString(),{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!res.ok)throw new Error(`Blizzard GET failed ${res.status} ${url.pathname}: ${await res.text()}`);return res.json();}
export async function getPvpSeasonsIndex(){return blizzardGet("/data/wow/pvp-season/index");}
export async function getPvpLeaderboard(seasonId:string,bracket:string){return blizzardGet(`/data/wow/pvp-season/${seasonId}/pvp-leaderboard/${bracket}`);}
function norm(v:any){if(!v)return"Unknown";if(typeof v==="string")return v;if(v.name)return String(v.name);return"Unknown";}
export async function getCharacterProfile(realmSlug:string,name:string){return blizzardGet(`/profile/wow/character/${realmSlug}/${name.toLowerCase()}`);}
export async function getCharacterSpecializations(realmSlug:string,name:string){try{return await blizzardGet(`/profile/wow/character/${realmSlug}/${name.toLowerCase()}/specializations`);}catch{return null;}}
export function parseProfile(profile:any){const f=norm(profile?.faction);return{faction:f==="Alliance"||f==="Horde"?f:"Unknown",race:norm(profile?.race),className:norm(profile?.character_class),gender:norm(profile?.gender)};}
const treeNames:Record<string,string[]>={Warrior:["Arms","Fury","Protection"],Paladin:["Holy","Protection","Retribution"],Hunter:["Beast Mastery","Marksmanship","Survival"],Rogue:["Assassination","Combat","Subtlety"],Priest:["Discipline","Holy","Shadow"],Shaman:["Elemental","Enhancement","Restoration"],Mage:["Arcane","Fire","Frost"],Warlock:["Affliction","Demonology","Destruction"],Druid:["Balance","Feral","Restoration"]};
export function inferSpec(className:string,specs:any){const active=specs?.active_specialization?.name;if(active)return active;const groups=specs?.specialization_groups||specs?.talent_groups||[];const g=groups.find((x:any)=>x?.is_active||x?.selected)||groups[0];const trees=g?.specializations||g?.talent_trees||g?.talents||[];let best="",pts=-1;for(let i=0;i<trees.length;i++){const t=trees[i];const n=t?.specialization?.name||t?.name||t?.talent_tree?.name||treeNames[className]?.[i];const p=Number(t?.spent_points??t?.points_spent??t?.points??t?.talents?.length??0);if(n&&p>pts){best=n;pts=p;}}return best||"Unknown";}
export function parseLeaderboardRows(data:any){const rows=data?.entries||[];return rows.map((e:any)=>{const c=e?.character||e?.player?.character||{};const name=c?.name||e?.name;const realmSlug=c?.realm?.slug||c?.realm?.slug_name||e?.realm?.slug;const realmName=c?.realm?.name||realmSlug;const id=c?.id||`${realmSlug}-${name}`.toLowerCase();return{id:String(id),name,realmSlug,realmName,rank:Number(e?.rank??e?.ranking??0),rating:Number(e?.rating??0),wins:Number(e?.season_match_statistics?.won??e?.won??e?.wins??0),losses:Number(e?.season_match_statistics?.lost??e?.lost??e?.losses??0)}}).filter((x:any)=>x.name&&x.realmSlug&&x.rating);}
